web_interface/employee/urls.py
from django.conf.urls import url

from .views import (
    AddEmployeeView,
    AllEmployeesView,
    EmployeeDetailView,
    EmployeeUpdateView,
    SalaryUpdateView,
    EmployeeDeleteView,
    AllRelationsView,
    AddRelationView,
    UpdateRelationView,
    DeleteRelationView,
)

urlpatterns = [
    url(r'^add/$', AddEmployeeView.as_view(), name='add'),
    url(r'^$', AllEmployeesView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', EmployeeDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', EmployeeUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/update_salary/$', SalaryUpdateView.as_view(), name='update-salary'),
    url(r'^(?P<pk>\d+)/delete/$', EmployeeDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/relations/$', AllRelationsView.as_view(), name='all-relations'),
    url(r'^(?P<pk>\d+)/add_relation/$', AddRelationView.as_view(), name='add-relation'),
    url(r'^(?P<pk>\d+)/update_relation/$', UpdateRelationView.as_view(), name='update-relation'),
    url(r'^(?P<pk>\d+)/delete_relation/$', DeleteRelationView.as_view(), name='delete-relation'),
]

web_interface/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.posts, name="post-home"),
    path('new', views.new_post, name="post-new"),
]

web_interface/web_interface/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from employee import views as employee_views
from user import views as user_view
from main_website import views as main_view
from posts import views as main_post

urlpatterns = [
    path('', main_view.home, name='home'),
    path('register/',user_view.register, name='register'),
    path('profile/',user_view.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('formular/', include('formular.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('documents/', include('documents.urls')),
    path('about/', main_view.about, name='about'),
    path('employees/', include(('employee.urls', 'employees'), namespace='employees')),
    path('default_tmpl/', include(('default_tmpl.urls', 'default_tmpl'), namespace='default_tmpl')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_interface/main_website/models.py
from django.db import models

web_interface/main_website/forms.py
from django import forms

web_interface/main_website/views.py
from django.shortcuts import render

#Change path to parent directory for aneasier acces to files
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

from user.models import Profile
from default_tmpl.models import Default_Templates

def home(request):
	return render(request, 'main_website/home.html')

def about(request):
	return render(request, 'main_website/about.html')

web_interface/main_website/templates/main_website/about.html
{% extends "main_website/base.html" %}
{% block content %}
<p>
  &nbsp;&nbsp;&nbsp;&nbsp;The general idea of ​​this project is to export certificates in different types of format. As a format, v-om could export certificates in PDF or word and the respective certificates will be exported from the web interface. For the web interface we will make an authentication system so different users will be able to have different permissions depending on the type of user. We will start from an authentication system with user and password, and based on the user and the password, the user type will be identified and a platform related to the user type will be loaded. There will be three types of user, master user, administrator user and end user. For the master user we will be able and will have access to absolutely all the services offered by this platform including a platform that sets and administers news, in fact this will be the main difference between a Master user and an administrator user. For an administrator user we will have the right to create templates, to create end users, to set the related business account and to export documents and certificates. And for an end user, his right is to export only credentials created by the end user's administrator user. The Master user will have the possibility to create global templates, meaning that these templates can and will be the first templates displayed when a business account managed by an administrator user is created.

</p>
<p>
	&nbsp;&nbsp;&nbsp;&nbsp;The final goal of this project is to generate documents and certificates necessary in the human resources process for each individual employee automatically, so visits to the human resources department will no longer be necessary as each employee will have an account from which they can export the necessary certificate or document, in this case we will consider the end user to be an employee of a company and the administrator will be a person designated by the human resources department to administer all documents and certificates including the templates for their generation. In creating the platform, we will consider an interface that is as easy to use as possible and intuitive for each individual user
</p>
{% endblock content %}

web_interface/main_website/templates/main_website/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main_website/main.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'main_website/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'main_website/dropdown-btn.js' %}"></script>

	{% if title %}
		<title>{{ title }}</title>>
	{% else %}
		<title>Documents Exporter</title>
	{% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-orange fixed-top">
        <div class="container">
          <img class="navbar-brand" src="{% static 'main_website/logo.svg' %}" height="50px" width="200px"/>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">My Account</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Sign in</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Sign up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
          <div class="col-md-3">
              <div class="sidenav">
                  <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
                  {% if user.is_authenticated %}
                      <a class="nav-item nav-link" href="{% url 'employees:all' %}">Employees</a>
                      <a class="nav-item nav-link" href="{% url 'default_tmpl:home' %}">Generate</a>
                      <a class="nav-item nav-link" href="{% url 'home' %}">Settings</a>
                  {% endif %}
                  <a class="nav-item nav-link" href="{% url 'posts:post-home' %}">Messages</a>
                  <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
              </div>
          </div>
        <div class="col-md-6">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}<h1>Missing content!</h1>{% endblock %}
        </div>
        <div class="col-md-3">
          <div class="content-section sidebar">
            <h3>Global Statistic</h3>
            {% block statistic %}
              <p class='text-muted'>
                <ul class="list-group">
                  <li class="list-group-item list-group-item-dark">Exported Documents: {{ nr_documents }} </li>
                  <li class="list-group-item list-group-item-dark">Users: {{ nr_users }} </li>
                  <li class="list-group-item list-group-item-dark">Templates:  {{ nr_templates }} </li>
                  <li class="list-group-item list-group-item-dark">Posts:  {{ nr_posts }} </li>
                </ul>
              </p>
            {% endblock %}
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

web_interface/main_website/templates/main_website/home.html
{% extends "main_website/base.html" %}
{% block content %}
{% if user.is_authenticated %}
    <h1> Welcome {{ user.username }}</h1>
    <p> Fill your templates is one go.. </p>
    <p> Check employess tab add a new employee </p>
    <p> Check Templates </p>
    <p> Check The blog of the users. </p>
{% else %}
  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;In choosing the objective of this project I took into account the problems that were around me and solving them with the help of current technology. In particular, the human resources department that uses a lot of documents and paper that is not an aspect attracted my attention just ecological, in addition to this, the distribution of certificates and documents necessary for any human resources process is a cost and a totally unproductive time for any employee of the human resources department time that could be used in the other processes of human resources management employees.
  </p>

  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;At the same time, the main user of this project are the companies/companies with a limited number of employees who cannot afford a qualified human resources department and therefore the administration of these documents and certificates would be a burden and an additional cost we need. That is precisely why from the administrator's account it is possible to export and generate word or PDF documents for each employee of the company in the event that user generation is not desired and each user must log in separately, although it is possible for the end user to log in separately to generate any necessary documents. Today we can say that we have a platform that manages both the generation of documents and the generation of users to have access to related documents.
  </p>

  <p>
  &nbsp;&nbsp;&nbsp;&nbsp;The problem identified was the creation of documents related to the human resources process manually and the enormous time required to modify and distribute them for both small-sized companies and large companies that want to automate their human resources processes required for processing of documents and certificates therefore we can say that the platform addresses a target group, any commercial company regardless of the number of employees.
  </p>
  {%endif%}

{% endblock content %}