web_interface/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.posts, name="post-home"),
    path('new', views.new_post, name="post-new"),
]

web_interface/web_interface/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from employee import views as employee_views
from user import views as user_view
from main_website import views as main_view
from posts import views as main_post

urlpatterns = [
    path('', main_view.home, name='home'),
    path('register/',user_view.register, name='register'),
    path('profile/',user_view.profile, name='profile'),
    path('admin/', admin.site.urls),
    path('formular/', include('formular.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('documents/', include('documents.urls')),
    path('about/', main_view.about, name='about'),
    path('employees/', include(('employee.urls', 'employees'), namespace='employees')),
    path('default_tmpl/', include(('default_tmpl.urls', 'default_tmpl'), namespace='default_tmpl')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_interface/posts/models.py
from django.db import models

from django.utils import timezone


# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    data_publish = models.DateField(default=timezone.now)
    time_publish = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.title

web_interface/posts/forms.py
from django import forms
from .models import Post

class NewPostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']

web_interface/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import NewPostForm
from django.contrib import messages

# Create your views here.
def posts(request):
	context = {
		'posts': Post.objects.all()
	}
	return render(request, 'user_post.html', context)

def new_post(request):
	if request.method == 'POST':
		new_post_form = NewPostForm(request.POST)
		if  new_post_form.is_valid():
			new_post_form.save()
			messages.success(request, f'Message stored!')
			return redirect('posts:post-home')

	else:
		new_post_form = NewPostForm()

	context = {
		'new_post_form' : new_post_form
	}

	return render(request, 'new_post.html', context)

web_interface/posts/templates/new_post.html
{% extends "main_website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <h2 class="text-center"><i class="fa fa-message"></i> Add New Message</h2>
</div>
<div class="row">
    

    <form method="POST" enctype="multipart/form-data" action="" class="form-group">
        {% csrf_token %}
        {{ new_post_form.as_p }}
        <button type="submit" class="btn btn-primary"> Add Message</button>
    </form>


</div>
{% endblock content %}

web_interface/posts/templates/user_post.html
{% extends "main_website/base.html" %}

{% block content %}
<div class="row">
    <div class="new-button">
        <a class="nav-item nav-link" href="{% url 'posts:post-new' %}">New Message</a>
    </div>
</div>

<div class="row">
    {% for post in posts %}
        <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.data_publish|date:"F d, Y" }}</a>
            <small class="text-muted">{{ post.time_publish|time:"G:i" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        </article>
    {% endfor %}
</div>
{% endblock content %}